In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('adult.csv',header=None)
data.head()

0                  1       2           3   4                    5   \
0  39          State-gov   77516   Bachelors  13        Never-married   
1  50   Self-emp-not-inc   83311   Bachelors  13   Married-civ-spouse   
2  38            Private  215646     HS-grad   9             Divorced   
3  53            Private  234721        11th   7   Married-civ-spouse   
4  28            Private  338409   Bachelors  13   Married-civ-spouse   

                   6               7       8        9     10  11  12  \
0        Adm-clerical   Not-in-family   White     Male  2174   0  40   
1     Exec-managerial         Husband   White     Male     0   0  13   
2   Handlers-cleaners   Not-in-family   White     Male     0   0  40   
3   Handlers-cleaners         Husband   Black     Male     0   0  40   
4      Prof-specialty            Wife   Black   Female     0   0  40   

               13      14  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3   United-States   <=50K  
4            Cuba   <=50K

# 1)	Rename the columns.

In [3]:
data.rename(columns = {0 : 'Age', 1 : 'Workclass', 2 : 'Fnlwgt', 3 : 'Education', 4 : 'education_num', 5 : 'marital_status', 6 : 'occupation', 7 : 'relationship', 8 : 'race', 9 : 'sex', 10 : 'capital_gain', 11 : 'capital_loss', 12 : 'hours_per_week', 13 : 'native_country',14 : 'income'},inplace=True)
df = data.copy()
data.head()

Age          Workclass  Fnlwgt   Education  education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital_status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital_gain  capital_loss  hours_per_week  native_country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

# 2)	Remove handle null values(if any).

In [4]:
data.isnull().sum()

Age               0
Workclass         0
Fnlwgt            0
Education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [5]:
data.shape

(32561, 15)

In [6]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
data['sex'] = label_encoder.fit_transform(data['sex'])
data['income'] = label_encoder.fit_transform(data['income'])
data['race'] = label_encoder.fit_transform(data['race'])
data['relationship'] = label_encoder.fit_transform(data['relationship'])
data['marital_status'] = label_encoder.fit_transform(data['marital_status'])
data['Workclass'] = label_encoder.fit_transform(data['Workclass'])
data['occupation'] = label_encoder.fit_transform(data['occupation'])

In [7]:
data['hours_per_week'] = pd.cut(data['hours_per_week'],bins=[0,10,20,30,40,50,60,70,80,90,100],labels=[1,2,3,4,5,6,7,8,9,10])
data.head()

Age  Workclass  Fnlwgt   Education  education_num  marital_status  \
0   39          7   77516   Bachelors             13               4   
1   50          6   83311   Bachelors             13               2   
2   38          4  215646     HS-grad              9               0   
3   53          4  234721        11th              7               2   
4   28          4  338409   Bachelors             13               2   

   occupation  relationship  race  sex  capital_gain  capital_loss  \
0           1             1     4    1          2174             0   
1           4             0     4    1             0             0   
2           6             1     4    1             0             0   
3           6             0     2    1             0             0   
4          10             5     2    0             0             0   

  hours_per_week  native_country  income  
0              4   United-States       0  
1              2   United-States       0  
2              4   United-States       0  
3              4   United-States       0  
4              4            Cuba       0

# 3)	Split data into training and test data.

In [8]:
df['sex'] = label_encoder.fit_transform(df['sex'])
df['Workclass'] = label_encoder.fit_transform(df['Workclass'])
df['race'] = label_encoder.fit_transform(df['race'])
df['income_greater_than_50k'] = label_encoder.fit_transform(df['income'])
data['marital_status'] = label_encoder.fit_transform(data['marital_status'])
df.head()

Age  Workclass  Fnlwgt   Education  education_num       marital_status  \
0   39          7   77516   Bachelors             13        Never-married   
1   50          6   83311   Bachelors             13   Married-civ-spouse   
2   38          4  215646     HS-grad              9             Divorced   
3   53          4  234721        11th              7   Married-civ-spouse   
4   28          4  338409   Bachelors             13   Married-civ-spouse   

           occupation    relationship  race  sex  capital_gain  capital_loss  \
0        Adm-clerical   Not-in-family     4    1          2174             0   
1     Exec-managerial         Husband     4    1             0             0   
2   Handlers-cleaners   Not-in-family     4    1             0             0   
3   Handlers-cleaners         Husband     2    1             0             0   
4      Prof-specialty            Wife     2    0             0             0   

   hours_per_week  native_country  income  income_greater_than_50k  
0              40   United-States   <=50K                        0  
1              13   United-States   <=50K                        0  
2              40   United-States   <=50K                        0  
3              40   United-States   <=50K                        0  
4              40            Cuba   <=50K                        0

In [9]:
X = df.iloc[:,[0,2,4,8,9,10,11,12]]
y = df.iloc[:,15]

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(24420, 8)
(8141, 8)
(24420,)
(8141,)


# 4)	Apply the following models on the training dataset

a) Gaussian Naive Bayes Classifier

In [12]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train,y_train)
print('Test acc',gnb.score(x_test,y_test))

Test acc 0.7921631249232282


b) Decision Tree

In [13]:
from sklearn.tree import DecisionTreeClassifier
dt1 = DecisionTreeClassifier(criterion='gini')
dt1.fit(x_train,y_train)
print('Test acc',dt1.score(x_test,y_test))

Test acc 0.7797567866355485


c) Random Forest Classifier

In [14]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)
print('Test acc',rfc.score(x_test,y_test))

Test acc 0.8222577078982926


d) Logistic Regression

In [15]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(solver='liblinear')
lr.fit(x_train,y_train)
print('Test acc',lr.score(x_test,y_test))

Test acc 0.7943741555091512


e) KNN Classifier

In [16]:
from sklearn.neighbors import KNeighborsClassifier
knc = KNeighborsClassifier(n_neighbors=25)
knc.fit(x_train,y_train)
print('Test acc',knc.score(x_test,y_test))

Test acc 0.7983048765507923


# 5)	Predict the income for test data

In [17]:
ypred_GNB = gnb.predict(x_test)
ypred_GNB

array([0, 0, 0, ..., 0, 0, 0])

In [18]:
ypred_DT = dt1.predict(x_test)
ypred_DT

array([0, 1, 0, ..., 0, 0, 0])

In [19]:
ypred_RFC = rfc.predict(x_test)
ypred_RFC

array([0, 1, 0, ..., 0, 0, 0])

In [20]:
ypred_LR = lr.predict(x_test)
ypred_LR

array([0, 0, 0, ..., 0, 0, 0])

In [21]:
ypred_KNC = knc.predict(x_test)
ypred_KNC

array([0, 0, 0, ..., 0, 0, 0])

# 6)	Compute Confusion matrix and classification report for each of these models.

In [22]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [23]:
aa = confusion_matrix(y_test,ypred_GNB)
print('Confusion Matrix\n',aa)
print(classification_report(y_test,ypred_GNB))

Confusion Matrix
 [[5829  334]
 [1358  620]]
              precision    recall  f1-score   support

           0       0.81      0.95      0.87      6163
           1       0.65      0.31      0.42      1978

    accuracy                           0.79      8141
   macro avg       0.73      0.63      0.65      8141
weighted avg       0.77      0.79      0.76      8141



In [24]:
ab = confusion_matrix(y_test,ypred_DT)
print('Confusion Matrix\n',ab)
print(classification_report(y_test,ypred_DT))

Confusion Matrix
 [[5206  957]
 [ 836 1142]]
              precision    recall  f1-score   support

           0       0.86      0.84      0.85      6163
           1       0.54      0.58      0.56      1978

    accuracy                           0.78      8141
   macro avg       0.70      0.71      0.71      8141
weighted avg       0.78      0.78      0.78      8141



In [25]:
bd = confusion_matrix(y_test,ypred_RFC)
print('Confusion Matrix\n',bd)
print(classification_report(y_test,ypred_RFC))

Confusion Matrix
 [[5601  562]
 [ 885 1093]]
              precision    recall  f1-score   support

           0       0.86      0.91      0.89      6163
           1       0.66      0.55      0.60      1978

    accuracy                           0.82      8141
   macro avg       0.76      0.73      0.74      8141
weighted avg       0.81      0.82      0.82      8141



In [26]:
ca = confusion_matrix(y_test,ypred_LR)
print('Confusion Matrix\n',ca)
print(classification_report(y_test,ypred_LR))

Confusion Matrix
 [[5944  219]
 [1455  523]]
              precision    recall  f1-score   support

           0       0.80      0.96      0.88      6163
           1       0.70      0.26      0.38      1978

    accuracy                           0.79      8141
   macro avg       0.75      0.61      0.63      8141
weighted avg       0.78      0.79      0.76      8141



In [27]:
cb = confusion_matrix(y_test,ypred_KNC)
print('Confusion Matrix\n',cb)
print(classification_report(y_test,ypred_KNC))

Confusion Matrix
 [[6100   63]
 [1579  399]]
              precision    recall  f1-score   support

           0       0.79      0.99      0.88      6163
           1       0.86      0.20      0.33      1978

    accuracy                           0.80      8141
   macro avg       0.83      0.60      0.60      8141
weighted avg       0.81      0.80      0.75      8141

